### ISSUE TITLE
Package can't be built with github dependency

### ISSUE THREAD

**Issue by brent-moffit** [hmrc/python-aws-lambda-packager#2]
If your project has a dependency on a github depot lambda-packager throws an error during package creation.

Example dependency in `pyproject.toml`
```
[tool.poetry.dependencies]
lambda-packager = {git = "https://github.com/hmrc/python-aws-lambda-packager.git"}
```

Run `lambda-packager` and you get this error:

```
ERROR: Can't verify hashes for these requirements because we don't have a way to hash version control repositories:
    lambda-packager@ git+https://github.com/hmrc/python-aws-lambda-packager.git@master from git+https://github.com/hmrc/python-aws-lambda-packager.git@master (from -r /var/folders/_n/dzhlknk14cx3b398vlcm8r140000gp/T/tmp6636q_6j/requirements.txt (line 10))
```

This prevents me from being able to use my own shared libraries as dependencies with lambda-packager.

**Comment by cob16** [comment]
This should now work in version `1.2.0` using the `without_hashes` setting
